apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ./resources/certificate.yaml
  - ./resources/deployment.yaml
  - ./resources/ingress.yaml
  #- ./resources/issuer.yaml
  - ./resources/service.yaml
