apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../environments/qa

patches:
- path: ./patches/dotnet-helloworld-certificate.yaml
  target:
    kind: Certificate
    name: dotnet-helloworld
- path: ./patches/dotnet-helloworld-ingress.yaml
  target:
    kind: Ingress
    name: dotnet-helloworld-cluster 