apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: dotnet-helloworld-prod
nameSuffix: -prod

resources:
  - ../../base

patches:
  - path: ./patches/certificate.yaml
    target:
      kind: Certificate
  - path: ./patches/deployment.yaml
    target:
      kind: Deployment
  - path: ./patches/ingress.yaml
    target:
      kind: Ingress

commonLabels:
  app: dotnet-helloworld-prod

# transformers:
#   - ./resources/labeltransformer.yaml

images:
  - name: image-placeholder
    newName: repo-prod/containers/dotnet-helloworld
    newTag: 2023.12.13
