apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dotnet-helloworld
spec:
  commonName: dotnet-helloworld.example.com
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames: []
  duration: 8760h0m0s # 365d
  emailAddresses: [email@email.com]
  # Issuer references are always required.
  issuerRef:
    name: clusterissuer-prod
    #name: selfsigned-issuer
    kind: ClusterIssuer
    #kind: Issuer
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  renewBefore: 720h0m0s # 30d
  # Secret names are always required.
  secretName: dotnet-helloworld-tls
  subject:
    organizations:
      - Public Cloud Operations
    organizationalUnits:
      - Container Platform Administration
    countries:
      - us
    provinces:
      - CA
    localities:
      - Sunnyvale
  usages:
    - server auth
    - client auth
