name: Validate Kustomize Files

on: 
  pull_request:
    branches: [ main ] 

jobs:
  validate-kustomize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          sudo mv kustomize /usr/local/bin/kustomize
      
      - name: Install kubeconform
        run: |
          curl -Lo kubeconform https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64 && chmod +x kubeconform && sudo mv kubeconform /usr/local/bin/

      - name: List Directory and Run Kustomize Build then kubeconform
        run: |
          for dir in $(find ./path/to/parent/directory -maxdepth 1 -type d); do
            if [ -f "$dir/kustomization.yaml" ]; then
              echo "Processing Kustomize directory: $dir"
              if ! kustomize build $dir > kustomize_output.yaml; then
                echo "Kustomize build failed in directory: $dir"
                exit 1
              fi
              if ! kubeconform -strict -ignore-missing-schemas kustomize_output.yaml; then
                echo "Kubeconform validation failed in directory: $dir"
                exit 1
              fi
              rm kustomize_output.yaml  # Clean up the temporary output file
            fi
          done