name: Validate Kustomize Files

on: 
  pull_request:
    branches: [ main ] 

jobs:
  validate-kustomize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
           mv kustomize /usr/local/bin/kustomize

          if ! command -v kustomize &> /dev/null; then
            echo "Kustomize is not installed. Please contact the container team."
            exit 1
          fi
      - name: Install Kubeval
        run: |
          curl -sSL -O "https://github.com/yannh/kubeconform/releases/download/v0.6.4/kubeconform-linux-arm64.tar.gz" && ls -lart
          mv kubeconform /usr/local/bin/kubeconform
          if ! command -v kubeconform &> /dev/null; then
            echo "Kubeconform is not installed. Please contact the container team."
            exit 1
          fi


      - name: List Directory and Run Kustomize Build

        run: |
          for dir in $(find ./overlays -maxdepth 1 -type d); do
            if [ -f "$dir/kustomization.yaml" ]; then
              echo "Processing Kustomize directory: $dir"
              if ! kustomize build $dir ; then
                echo "Kustomize build failed in directory: $dir"
                exit 1
              fi
            fi
          done
