name: Validate Kubernetes Manifests

on: 
  pull_request:
    branches: [ main ] 

jobs:
  validate-kustomize:
    uses: ./.github/workflows/validate-ru.yaml
    permissions: 
        id-token: write
        contents: read
        actions: read
        security-events: write
    with: 
      overlays-dir: ./overlays
