apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: dotnet-helloworld-dev
nameSuffix: -dev

resources:
- ../../base

patches:
- path: ./patches/certificate.yaml
  target:
    kind: Certificate
- path: ./patches/deployment.yaml
  target:
    kind: Deployment
- path: ./patches/ingress.yaml
  target:
    kind: Ingress

commonLabels:
  app: dotnet-helloworld-dev

# transformers:
# - ./resources/labeltransformer.yaml

images:
- name: image-placeholder
  newName: myrepo/containers/blazorhelloworldapp
  newTag: 36ee184ecb976f37f69229d05903fdf18927d7d8
