apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dotnet-helloworld-dev

resources:
- ../../base

patches:
- path: ./patches/dotnet-helloworld-certificate.yaml
  target:
    kind: Certificate
    name: dotnet-helloworld
- path: ./patches/dotnet-helloworld-deployment.yaml
  target:
    kind: Deployment
    name: dotnet-helloworld
- path: ./patches/dotnet-helloworld-ingress.yaml
  target:
    kind: Ingress
    name: dotnet-helloworld

commonLabels:
  app_code: "3kv" 
  classification: "highly-confidential" 
  cost_id: "12345" 
  department_id: "12345" 
  project_id:  "it-rtyfhdfdf"
  tco_id: "lob-inv" 
  app_environment: "dev"
  sc_group: "corp-sc-group"
  app_instance: "snsvc123456"

# transformers:
# - ./resources/labeltransformer.yaml

images:
- name: dotnet-helloworld-image
  newName: myrepo/containers/blazorhelloworldapp
  newTag: 36ee184ecb976f37f69229d05903fdf18927d7d8
